#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=1
START=99

CONF="v2raya"
PROG="/data/usr/bin/v2raya"

is_enabled() {
    local enabled
    config_get_bool enabled "$1" "$2" "${3:-0}"
    if [ "$enabled" -eq "1" ]; then
        return 0
    else
        return 1
    fi
}

append_env() {
    procd_append_param env "V2RAYA_$(echo "$1" | tr "[a-z]" "[A-Z]")"="$2"
}

append_env_arg() {
    local value
    config_get value "$1" "$2" $3
    [ -n "$value" ] && append_env "$2" "$value"
}

append_env_bool() {
    is_enabled "$1" "$2" && append_env "$2" "true"
}

start_service() {
    config_load "$CONF"

    is_enabled "config" "enabled" || return 1

    procd_open_instance "$CONF"
    procd_set_param command "$PROG"
    procd_set_param env XDG_DATA_HOME="/data/usr/share"

    # Add commands
    #procd_append_param command --v2ray-bin="/data/usr/bin/v2ray"
    procd_append_param command --v2ray-assetsdir="/data/usr/share/v2ray"
    #procd_append_param command --config="/mnt/usb-1210d517/v2raya/config"

    # Add envs
    #procd_append_param env V2RAYA_V2RAY_BIN="/data/usr/bin/v2ray"

    append_env "config" "/etc/v2raya"
    append_env "log_file" "/data/usr/log/v2raya/v2raya.log"

    append_env_arg "config" "address" "0.0.0.0:2017"
    append_env_arg "config" "ipv6_support" "auto"
    append_env_arg "config" "nftables_support" "auto"
    append_env_arg "config" "log_level" "info"
    append_env_arg "config" "log_max_days" "3"
    append_env_arg "config" "v2ray_bin"
    append_env_arg "config" "v2ray_confdir"
    append_env_arg "config" "transparent_hook"
    append_env_arg "config" "core_hook"
    append_env_arg "config" "plugin_manager"
    append_env_bool "config" "log_disable_color"
    append_env_bool "config" "log_disable_timestamp"

    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "$CONF"
}
